blank_issues_enabled: true
contact_links:
  - name: 📖 Documentation
    url: https://github.com/Work-m8/ag-ui-4j/tree/main/docs
    about: Check our documentation for usage guides and API references
  - name: 💬 GitHub Discussions
    url: https://github.com/Work-m8/ag-ui-4j/discussions
    about: Ask questions, share ideas, and discuss with the community
  - name: 🔒 Security Issues
    url: https://github.com/Work-m8/ag-ui-4j/security/advisories/new
    about: Please report security vulnerabilities privately through Security Advisories
  - name: 📧 Contact Maintainers
    url: mailto:pascal.wilbrink@gmail.com
    about: For direct communication with project maintainers