package io.workm8.agui4j.core.message;

import io.workm8.agui4j.core.tool.ToolCall;

import java.util.ArrayList;
import java.util.List;

/**
 * A message representing communication from an AI assistant or automated system.
 * <p>
 * This message type is used for responses and communications generated by AI
 * assistants or automated components within the system. It extends the base
 * message functionality with the ability to include tool calls that the
 * assistant may invoke as part of its response.
 * </p>
 * <p>
 * Assistant messages can contain both textual content (inherited from
 * {@link BaseMessage}) and a list of tool calls that represent actions
 * the assistant wants to perform or has performed.
 * </p>
 *
 * @author pascalwilbrink
 * @see BaseMessage
 * @see ToolCall
 */
public class AssistantMessage extends BaseMessage {

    private List<ToolCall> toolCalls = new ArrayList<>();

    /**
     * Returns the role of this message as "assistant".
     * <p>
     * This implementation fulfills the abstract contract from {@link BaseMessage}
     * and identifies this message as originating from an assistant.
     * </p>
     *
     * @return "assistant" - the fixed role for assistant messages
     */
    public String getRole() {
        return "assistant";
    }

    /**
     * Sets the list of tool calls associated with this assistant message.
     *
     * @param toolCalls the list of tool calls. Can be null or empty.
     */
    public void setToolCalls(final List<ToolCall> toolCalls) {
        this.toolCalls = toolCalls;
    }

    /**
     * Returns the list of tool calls associated with this assistant message.
     *
     * @return the list of tool calls, never null but may be empty
     */
    public List<ToolCall> getToolCalls() {
        return this.toolCalls;
    }
}