services:
  jekyll:
    image: jekyll/jekyll:4.2.2
    container_name: ag-ui-4j-jekyll
    ports:
      - "2020:4000"
    environment:
      - JEKYLL_ENV=development
    volumes:
      - .:/srv/jekyll
    command: >
      bash -c "
        bundle install &&
        bundle exec jekyll serve --host 0.0.0.0 --incremental --livereload
      "
